veg1 = str(input("Первый овощ: "))
veg2 = str(input("Второй овощ: "))
veg3 = str(input("Третий овощ: "))
print(str.lower(veg1), str.lower(veg2), str.lower(veg3))
print(str.upper(veg1), str.upper(veg2), str.upper(veg3))
print(str.capitalize(veg1), str.capitalize(veg2), str.capitalize(veg3))
print("Введите число", str.capitalize(veg1), ":")
n1 = (input())
print("Введите число", str.capitalize(veg2), ":")
n2 = (input())
print("Введите число", str.capitalize(veg3), ":")
n3 = (input())
print("{0}: {1}, {2}: {3}, {4}: {5}.".format(str.capitalize(veg1), n1, str.capitalize(veg2), n2, str.capitalize(veg3),
                                             n3))